# Generated by Django 4.0.6 on 2022-07-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_data_migrations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
    ]
